functionsDir: ./spectral/

functions:
  - full-stop
  - response-description-returns
  - oneof-model-name

formats: []

extends: [[spectral:oas, all]]

rules:
  operation-default-response: off
  operation-2xx-response: off

  parameters-need-description:
    description: Parameter requires example
    given: $..parameters[*].schema
    severity: error
    then:
      field: example
      function: truthy

  description-requires-full-stop:
    description: Description should end in full stop.
    given: $..description
    severity: error
    then:
      function: full-stop

  response-description-returns:
    description: Response descriptions should start with `Returns`.
    given: $..paths[*][*].responses[*].description
    severity: error
    then:
      function: response-description-returns

  oneof-model-name:
    description: A oneOf item needs a valid model name
    given: $..*[?(@.oneOf)]
    severity: error
    then:
      function: oneof-model-name
