functionsDir: ./spectral/

functions:
  - full-stop

formats: []

extends: [[spectral:oas, all]]

rules:
  operation-default-response: off
  operation-2xx-response: off

  parameters-need-description:
    description: Parameter requires example
    given: $..parameters[*].schema
    severity: error
    then:
      field: example
      function: truthy

  description-requires-full-stop:
    description: Description should end in full stop.
    given: $..description
    severity: error
    then:
      function: full-stop
