openapi: 3.0.0
info:
  version: 1.0.0
  title: Processing APIs
servers:
  - url: 'https://{{cluster}}'
paths:
  /authorizations:
    post:
      summary: Create an authorization
      operationId: createAuthorization
      
      responses:
        '200':
          description: |-
            Returns a mini representation of a new authorization resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorization'
        default:
          description: |-
            An unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Authorization:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          format: uuid
          description: |-
            The unique ID that will be used to create a new authorization.
          example: |-
            8724fd24-5489-4a5d-90fd-0604df7d3b83
        
        type:
          type: string
          description: |-
            The type of this object.
          example: authorization
          enum:
            - authorization

    Error:
      type: object
      required:
        - status
        - code
        - message
        - documentation_url
      properties:
        status: 
          type: int32
          description: The HTTP status code for this error.
          example: 401
        code:
          type: string
          description: |-
            A unique error code to help further define the error within the HTTP status code.
          example: invalid_token
        message:
          type: string
          description: |-
            A human readable error to help a developer discover the cause if the error.
          example: Invalid token received.
        documentation_url:
          type: string
          format: url
          description: |-
            A link to the developer documentation for this error.

          