---
schema:
  type: string
  example: staging
  enum:
    - development
    - staging
    - production
  default: production
in: query
name: environment
description: |-
  Filters the results to only the items available in this environment.
