---
# yamllint disable rule:line-length
openapi: 3.0.0

info:
  title: Gr4vy API (Beta)
  version: "1.0"
  contact:
    name: Gr4vy Support
    email: support@gr4vy.com
    url: "https://gr4vy.com"
  termsOfService: "https://gr4vy.com"
  license:
    name: MIT
    url: https://raw.githubusercontent.com/gr4vy/gr4vy-openapi/main/LICENSE
  description: |-
    Welcome to the Gr4vy API reference documentation.
    Our API is still very much a work in product and subject to change.

servers:
  - url: "https://api.{merchant}.app.gr4vy.com"
    variables:
      merchant:
        default: demo
        description: |-
          The subdomain for your cluster as specified by the
          cluster's main merchant `short_name`.

tags:
  $ref: "./common/tags.yaml"

paths:
  "/async/payment-methods":
    post:
      $ref: "./paths/async__store-payment-method.yaml"

  "/async/transactions":
    post:
      $ref: "./paths/async__create-transaction.yaml"

  "/async/transactions/{transaction_id}/authorize":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/async__authorize-transaction.yaml"

  "/async/transactions/{transaction_id}/capture":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/async__capture-transaction.yaml"

  "/async/transactions/batch-capture":
    post:
      $ref: "./paths/async__batch-capture-transactions.yaml"

  "/auth/sessions":
    post:
      $ref: "./paths/sessions__login.yaml"
    put:
      $ref: "./paths/sessions__refresh.yaml"
    delete:
      $ref: "./paths/sessions__logout.yaml"

  "/api-key-pairs":
    get:
      $ref: "./paths/api_key_pairs__list-api-key-pairs.yaml"
    post:
      $ref: "./paths/api_key_pairs__create-api-key-pair.yaml"

  "/api-key-pairs/{api_key_pair_id}":
    parameters:
      - $ref: "./path-parameters/api_key_pair_id.yaml"
    delete:
      $ref: "./paths/api_key_pairs__delete-api-key-pair.yaml"

  "/buyers":
    get:
      $ref: "./paths/buyers__list-buyers.yaml"
    post:
      $ref: "./paths/buyers__add-buyer.yaml"

  "/buyers/{buyer_id}":
    parameters:
      - $ref: "./path-parameters/buyer_id.yaml"
    get:
      $ref: "./paths/buyers__get-buyer.yaml"
    put:
      $ref: "./paths/buyers__update-buyer.yaml"
    delete:
      $ref: "./paths/buyers__delete-buyer.yaml"

  "/merchants/main":
    get:
      $ref: "./paths/merchants__get-current-merchant.yaml"

  "/payment-methods":
    get:
      $ref: "./paths/payment_methods__list-payment-methods.yaml"
    post:
      $ref: "./paths/payment_methods__store-payment-method.yaml"

  "/payment-methods/{payment_method_id}":
    parameters:
      - $ref: "./path-parameters/payment_method_id.yaml"
    get:
      $ref: "./paths/payment_methods__get-payment-method.yaml"
    delete:
      $ref: "./paths/payment_methods__delete-payment-method.yaml"

  # "/payment-methods/{payment_method_id}/events":
  #   parameters:
  #     - $ref: "./path-parameters/payment_method_id.yaml"
  #   get:
  #     $ref: "./paths/payment_methods__list-payment-method-events.yaml"

  "/payment-methods/{payment_method_id}/approve":
    parameters:
      - $ref: "./path-parameters/payment_method_id.yaml"
    get:
      $ref: "./paths/payment_methods__approve-payment-method.yaml"

  "/payment-methods/approvals/{payment_method_approval_token}":
    parameters:
      - $ref: "./path-parameters/payment_method_approval_token.yaml"
    get:
      $ref: "./paths/payment_methods__redirect-payment-method-approval.yaml"

  "/payment-options":
    get:
      $ref: "./paths/payment_options__list-payment-options.yaml"

  "/payment-services":
    get:
      $ref: "./paths/payment_services__list-payment-services.yaml"
    post:
      $ref: "./paths/payment_services__add-payment-service.yaml"

  "/payment-services/{payment_service_id}":
    parameters:
      - $ref: "./path-parameters/payment_service_id.yaml"
    get:
      $ref: "./paths/payment_services__get-payment-service.yaml"
    put:
      $ref: "./paths/payment_services__update-payment-service.yaml"
    delete:
      $ref: "./paths/payment_services__delete_payment-service.yaml"

  "/payment-service-definitions":
    get:
      $ref: "./paths/payment_service_definitions__list-payment-service-definitions.yaml"

  "/payment-service-definitions/{payment_service_definition_id}":
    parameters:
      - $ref: "./path-parameters/payment_service_definition_id.yaml"
    get:
      $ref: "./paths/payment_service_definitions__get-payment-service-definition.yaml"

  "/card-rules":
    get:
      $ref: "./paths/card_rules__list-card-rules.yaml"
    post:
      $ref: "./paths/card_rules__add-card-rule.yaml"

  "/card-rules/{card_rule_id}":
    parameters:
      - $ref: "./path-parameters/card_rule_id.yaml"
    get:
      $ref: "./paths/card_rules__get-card-rule.yaml"
    put:
      $ref: "./paths/card_rules__update-card-rule.yaml"
    delete:
      $ref: "./paths/card_rules__delete-card-rule.yaml"

  "/transactions":
    get:
      $ref: "./paths/transactions__list-transactions.yaml"
    post:
      $ref: "./paths/transactions__create-transaction.yaml"

  "/transactions/{transaction_id}":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    get:
      $ref: "./paths/transactions__get-transaction.yaml"

  "/transactions/{transaction_id}/capture":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__capture-transaction.yaml"

  "/transactions/{transaction_id}/authorize":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__authorize-transaction.yaml"

  "/transactions/{transaction_id}/refund":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__refund-transaction.yaml"

  # "/transactions/{transaction_id}/events":
  #   parameters:
  #     - $ref: "./path-parameters/transaction_id.yaml"
  #   get:
  #     $ref: "./paths/transactions__list-transaction-events.yaml"

  "/transactions/{transaction_id}/approve":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    get:
      $ref: "./paths/transactions__approve-transaction.yaml"

  "/transactions/approvals/{transaction_approval_token}":
    parameters:
      - $ref: "./path-parameters/transaction_approval_token.yaml"
    get:
      $ref: "./paths/transactions__redirect-transaction-approval.yaml"

  "/users/me":
    get:
      $ref: "./paths/users__get-current-user.yaml"

components:
  schemas:
    Buyer:
      $ref: "./resources/buyer.yaml"
    Buyers:
      $ref: "./resources/buyers.yaml"
    BuyerCreateRequest:
      $ref: "./request-bodies/buyer_create_request.yaml"
    BuyerUpdateRequest:
      $ref: "./request-bodies/buyer_update_request.yaml"
    Card:
      $ref: "./resources/card.yaml"
    Card--Token:
      $ref: "./resources/card--token.yaml"
    CardDetails:
      $ref: "./resources/card_details.yaml"
    CardRequest:
      $ref: "./request-bodies/card_request.yaml"
    CardRule:
      $ref: "./resources/card_rule.yaml"
    CardRules:
      $ref: "./resources/card_rules.yaml"
    CardRuleBooleanCondition:
      $ref: "./resources/card_rule_boolean_condition.yaml"
    CardRuleNumberCondition:
      $ref: "./resources/card_rule_number_condition.yaml"
    CardRuleTextCondition:
      $ref: "./resources/card_rule_text_condition.yaml"
    CardRuleCreateRequest:
      $ref: "./request-bodies/card_rule_create_request.yaml"
    CardRuleUpdateRequest:
      $ref: "./request-bodies/card_rule_update_request.yaml"
    Error:
      $ref: "./resources/error.yaml"
    Error400BadRequest:
      $ref: "./resources/error_400_bad_request.yaml"
    Error400IncorrectJson:
      $ref: "./resources/error_400_incorrect_json.yaml"
    Error401Unauthorized:
      $ref: "./resources/error_401_unauthorized.yaml"
    Error404PendingCreation:
      $ref: "./resources/error_404_pending_creation.yaml"
    Error404NotFound:
      $ref: "./resources/error_404_not_found.yaml"
    Error409DuplicateRecord:
      $ref: "./resources/error_409_duplicate_record.yaml"
    ErrorDetail:
      $ref: "./resources/error_detail.yaml"
    APIKeyPair:
      $ref: "./resources/api_key_pair.yaml"
    APIKeyPairs:
      $ref: "./resources/api_key_pairs.yaml"
    Merchant:
      $ref: "./resources/merchant.yaml"
    PaymentMethods:
      $ref: "./resources/payment_methods.yaml"
    # PaymentMethodEvent:
    #   $ref: "./resources/payment_method_event.yaml"
    # PaymentMethodEvents:
    #   $ref: "./resources/payment_method_events.yaml"
    PaymentService:
      $ref: "./resources/payment_service.yaml"
    PaymentServices:
      $ref: "./resources/payment_services.yaml"
    PaymentServiceCreateRequest:
      $ref: "./request-bodies/payment_service_create_request.yaml"
    PaymentServiceUpdateRequest:
      $ref: "./request-bodies/payment_service_update_request.yaml"
    PaymentServiceDefinition:
      $ref: "./resources/payment_service_definition.yaml"
    PaymentServiceDefinitions:
      $ref: "./resources/payment_service_definitions.yaml"
    PaymentOption:
      $ref: "./resources/payment_option.yaml"
    PaymentOptions:
      $ref: "./resources/payment_options.yaml"
    PayPal:
      $ref: "./resources/paypal.yaml"
    PayPal--Token:
      $ref: "./resources/paypal--token.yaml"
    PayPalDetails:
      $ref: "./resources/paypal_details.yaml"
    PayPalRequest:
      $ref: "./request-bodies/paypal_request.yaml"
    Session:
      $ref: "./resources/session.yaml"
    SessionCreateRequest:
      $ref: "./request-bodies/session_create_request.yaml"
    Status:
      $ref: "./resources/status.yaml"
    Statuses:
      $ref: "./resources/statuses.yaml"
    TokenRequest:
      $ref: "./request-bodies/token_request.yaml"
    Transaction:
      $ref: "./resources/transaction.yaml"
    Transactions:
      $ref: "./resources/transactions.yaml"
    TransactionsBatchCaptureRequest:
      $ref: "./request-bodies/transactions_batch_capture_request.yaml"
    TransactionCreateRequest:
      $ref: "./request-bodies/transaction_create_request.yaml"
    TransactionCaptureRequest:
      $ref: "./request-bodies/transaction_capture_request.yaml"
    # TransactionEvent:
    #   $ref: "./resources/transaction_event.yaml"
    # TransactionEvents:
    #   $ref: "./resources/transaction_events.yaml"
    User:
      $ref: "./resources/user.yaml"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
