---
# yamllint disable rule:line-length
openapi: 3.0.0

info:
  title: Gr4vy API (Beta)
  version: "1.0"
  contact:
    name: Gr4vy Support
    email: support@gr4vy.com
    url: "https://gr4vy.com"
  termsOfService: "https://gr4vy.com"
  license:
    name: MIT
    url: https://raw.githubusercontent.com/gr4vy/gr4vy-openapi/main/LICENSE
  description: |-
    Welcome to the Gr4vy API reference documentation.
    Our API is still very much a work in product and subject to change.

servers:
  - url: "https://api.{merchant}.gr4vy.app"
    variables:
      merchant:
        default: demo
        description: |-
          The subdomain for your cluster as specified by the
          cluster's main merchant `short_name`.

tags:
  - name: API Key Pairs
    description: |-
      In Gr4vy, an API key pair is used to sign and validate JSON Web Tokens (JWT).
      JWTs are used as a HTTP `bearer` token to authenticate to the API. For more
      information please visit our [in-depth authentication](/guides/authentication)
      guide.
    x-internal: true

  - name: Async APIs
    x-internal: true
    description: |-
      The asynchronous (async) APIs are convenience APIs that function as an
      alternative way to create transactions and register payment methods
      without having to wait for the API to complete. Each of thee APIs returns
      directly without processing the request fully, allowing you to render a
      new page for the buyer while the request is processed.

  - name: Buyers
    description: |-
      In Gr4vy, a buyer represents your customer, the shopper who's performing
      a checkout and making a purchase.

      A buyer can be used by you to:

      * Display a human readable name (`display_name`) for a buyer in the Gr4vy
      admin panel
      * Associate multiple tokenized payment methods with a single user
      * Initialize **Gr4vy Embed** with the buyer ID, automatically displaying the
        buyer's previously stored payment methods, allowing for faster checkout.

  - name: Card Rules
    description: |-
      In Gr4vy, a card rule defines how a card transaction is processed. It
      determines which payment services are used, and with what priority, based
      on the transaction amount, card type, and many more attributes.

  - name: Merchants
    description: |-
      In Gr4vy, a merchant represents the entity that owns the Gr4vy cluster.
      Currently only one merchant is supported per cluster.
    x-internal: true

  - name: Payment Methods
    description: |-
      In Gr4vy, a payment method represents a way in which a payment can be
      processed, for example a card payment, a PayPal payment, or a Bitcoin
      payment.

      The payment method API can be used to:

      * Determine the available payment methods in a cluster.
      * Determine the available payment method for a buyer in a specific currency
      and country.
      * Store (also known as tokenize) a payment method for a buyer.
      * Fetch all previously tokenized payment methods for a buyer.

  - name: Payment Options
    description: |-
      In Gr4vy, a payment option represents a list of methods (card, PayPal,
      etc) that are available for a given locale.

      The payment options API can be used to:

      * Determine what types of payments can be processed in a specific locale.
      * Display a list options to a buyer to choose from.

  - name: Payment Service Definitions
    description: |-
      Payment service definitions describe the fields required for a payment
      service to be configured.

  - name: Payment Services
    description: |-
      In Gr4vy, a payment service represents a configured payment provider
      (Stripe, PayPal, Adyen, etc) for a specific payment type (card, bitcoin,
      etc)

      The payment services API can be used to:

      * Provide Gr4vy with the payment credentials for a payment provider.
      * Set a display name for a payment provider.

  - name: Sessions
    description: |-
      The sessions APIs are used to facilitate user authentication for the Gr4vy
      cluster admin.
    x-internal: true

  - name: Transactions
    description: |-
      In Gr4vy, a transaction represents a payment in any state, either before it
      is authorized, once it is captured, or after it has been refunded.

      The transactions API can be used to:

      - Authorize, capture, and store cards.
      - Authorize, capture, and store alternative payment methods like PayPal.
      - Refund, void, and otherwise cancel existing transactions.

  - name: Users
    description: |-
      In Gr4vy, a user represents an employee of the merchant with access to the
      cluster admin panel.
    x-internal: true

paths:
  "/async/payment-methods":
    post:
      $ref: "./paths/async__store-payment-method.yaml"

  "/async/transactions":
    post:
      $ref: "./paths/async__create-transaction.yaml"

  "/async/transactions/{transaction_id}/authorize":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/async__authorize-transaction.yaml"

  "/async/transactions/{transaction_id}/capture":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/async__capture-transaction.yaml"

  "/async/transactions/batch-capture":
    post:
      $ref: "./paths/async__batch-capture-transactions.yaml"

  "/auth/sessions":
    post:
      $ref: "./paths/sessions__login.yaml"
    put:
      $ref: "./paths/sessions__refresh.yaml"
    delete:
      $ref: "./paths/sessions__logout.yaml"

  "/api-key-pairs":
    get:
      $ref: "./paths/api_key_pairs__list-api-key-pairs.yaml"
    post:
      $ref: "./paths/api_key_pairs__create-api-key-pair.yaml"

  "/api-key-pairs/{api_key_pair_id}":
    parameters:
      - $ref: "./path-parameters/api_key_pair_id.yaml"
    delete:
      $ref: "./paths/api_key_pairs__delete-api-key-pair.yaml"

  "/buyers":
    get:
      $ref: "./paths/buyers__list-buyers.yaml"
    post:
      $ref: "./paths/buyers__add-buyer.yaml"

  "/buyers/{buyer_id}":
    parameters:
      - $ref: "./path-parameters/buyer_id.yaml"
    get:
      $ref: "./paths/buyers__get-buyer.yaml"
    put:
      $ref: "./paths/buyers__update-buyer.yaml"
    delete:
      $ref: "./paths/buyers__delete-buyer.yaml"

  "/buyers/payment-methods":
    get:
      $ref: "./paths/payment_methods__list-buyer-payment-methods.yaml"

  "/merchants/main":
    get:
      $ref: "./paths/merchants__get-current-merchant.yaml"

  "/payment-methods":
    get:
      $ref: "./paths/payment_methods__list-payment-methods.yaml"
    post:
      $ref: "./paths/payment_methods__store-payment-method.yaml"

  "/payment-methods/{payment_method_id}":
    parameters:
      - $ref: "./path-parameters/payment_method_id.yaml"
    get:
      $ref: "./paths/payment_methods__get-payment-method.yaml"
    delete:
      $ref: "./paths/payment_methods__delete-payment-method.yaml"

  # "/payment-methods/{payment_method_id}/events":
  #   parameters:
  #     - $ref: "./path-parameters/payment_method_id.yaml"
  #   get:
  #     $ref: "./paths/payment_methods__list-payment-method-events.yaml"

  # "/payment-methods/{payment_method_id}/approve":
  #   parameters:
  #     - $ref: "./path-parameters/payment_method_id.yaml"
  #   get:
  #     $ref: "./paths/payment_methods__approve-payment-method.yaml"

  # "/payment-methods/approvals/{payment_method_approval_token}":
  #   parameters:
  #     - $ref: "./path-parameters/payment_method_approval_token.yaml"
  #   get:
  #     $ref: "./paths/payment_methods__redirect-payment-method-approval.yaml"

  "/payment-options":
    get:
      $ref: "./paths/payment_options__list-payment-options.yaml"

  "/payment-services":
    get:
      $ref: "./paths/payment_services__list-payment-services.yaml"
    post:
      $ref: "./paths/payment_services__add-payment-service.yaml"

  "/payment-services/{payment_service_id}":
    parameters:
      - $ref: "./path-parameters/payment_service_id.yaml"
    get:
      $ref: "./paths/payment_services__get-payment-service.yaml"
    put:
      $ref: "./paths/payment_services__update-payment-service.yaml"
    delete:
      $ref: "./paths/payment_services__delete_payment-service.yaml"

  "/payment-service-definitions":
    get:
      $ref: "./paths/payment_service_definitions__list-payment-service-definitions.yaml"

  "/payment-service-definitions/{payment_service_definition_id}":
    parameters:
      - $ref: "./path-parameters/payment_service_definition_id.yaml"
    get:
      $ref: "./paths/payment_service_definitions__get-payment-service-definition.yaml"

  "/card-rules":
    get:
      $ref: "./paths/card_rules__list-card-rules.yaml"
    post:
      $ref: "./paths/card_rules__add-card-rule.yaml"

  "/card-rules/{card_rule_id}":
    parameters:
      - $ref: "./path-parameters/card_rule_id.yaml"
    get:
      $ref: "./paths/card_rules__get-card-rule.yaml"
    put:
      $ref: "./paths/card_rules__update-card-rule.yaml"
    delete:
      $ref: "./paths/card_rules__delete-card-rule.yaml"

  "/transactions":
    get:
      $ref: "./paths/transactions__list-transactions.yaml"
    post:
      $ref: "./paths/transactions__create-transaction.yaml"

  "/transactions/{transaction_id}":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    get:
      $ref: "./paths/transactions__get-transaction.yaml"

  "/transactions/{transaction_id}/capture":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__capture-transaction.yaml"

  "/transactions/{transaction_id}/authorize":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__authorize-transaction.yaml"

  "/transactions/{transaction_id}/refund":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    post:
      $ref: "./paths/transactions__refund-transaction.yaml"

  # "/transactions/{transaction_id}/events":
  #   parameters:
  #     - $ref: "./path-parameters/transaction_id.yaml"
  #   get:
  #     $ref: "./paths/transactions__list-transaction-events.yaml"

  "/transactions/{transaction_id}/approve":
    parameters:
      - $ref: "./path-parameters/transaction_id.yaml"
    get:
      $ref: "./paths/transactions__approve-transaction.yaml"

  "/transactions/approvals/{transaction_approval_token}":
    parameters:
      - $ref: "./path-parameters/transaction_approval_token.yaml"
    get:
      $ref: "./paths/transactions__redirect-transaction-approval.yaml"

  "/users/me":
    get:
      $ref: "./paths/users__get-current-user.yaml"

components:
  schemas:
    Buyer:
      $ref: "./resources/buyer.yaml"
    Buyers:
      $ref: "./resources/buyers.yaml"
    BuyerRequest:
      $ref: "./request-bodies/buyer_create_request.yaml"
    BuyerUpdate:
      $ref: "./request-bodies/buyer_update_request.yaml"
    Card:
      $ref: "./resources/card.yaml"
    Card--Tokenized:
      $ref: "./resources/card--tokenized.yaml"
    CardDetails:
      $ref: "./resources/card_details.yaml"
    CardRequest:
      $ref: "./request-bodies/card_request.yaml"
    CardRule:
      $ref: "./resources/card_rule.yaml"
    CardRules:
      $ref: "./resources/card_rules.yaml"
    CardRuleNumberCondition:
      $ref: "./resources/card_rule_number_condition.yaml"
    CardRuleTextCondition:
      $ref: "./resources/card_rule_text_condition.yaml"
    CardRuleRequest:
      $ref: "./request-bodies/card_rule_create_request.yaml"
    CardRuleUpdate:
      $ref: "./request-bodies/card_rule_update_request.yaml"
    ErrorGeneric:
      $ref: "./resources/error_generic.yaml"
    Error400BadRequest:
      $ref: "./resources/error_400_bad_request.yaml"
    Error400IncorrectJson:
      $ref: "./resources/error_400_incorrect_json.yaml"
    Error401Unauthorized:
      $ref: "./resources/error_401_unauthorized.yaml"
    Error404PendingCreation:
      $ref: "./resources/error_404_pending_creation.yaml"
    Error404NotFound:
      $ref: "./resources/error_404_not_found.yaml"
    Error409DuplicateRecord:
      $ref: "./resources/error_409_duplicate_record.yaml"
    ErrorDetail:
      $ref: "./resources/error_detail.yaml"
    APIKeyPair:
      $ref: "./resources/api_key_pair.yaml"
    APIKeyPairs:
      $ref: "./resources/api_key_pairs.yaml"
    Merchant:
      $ref: "./resources/merchant.yaml"
    PaymentMethod:
      $ref: "./resources/payment_method.yaml"
    PaymentMethods:
      $ref: "./resources/payment_methods.yaml"
    PaymentMethods--Tokenized:
      $ref: "./resources/payment_methods--tokenized.yaml"
    # PaymentMethodEvent:
    #   $ref: "./resources/payment_method_event.yaml"
    # PaymentMethodEvents:
    #   $ref: "./resources/payment_method_events.yaml"
    PaymentService:
      $ref: "./resources/payment_service.yaml"
    PaymentServices:
      $ref: "./resources/payment_services.yaml"
    PaymentServiceRequest:
      $ref: "./request-bodies/payment_service_create_request.yaml"
    PaymentServiceUpdate:
      $ref: "./request-bodies/payment_service_update_request.yaml"
    PaymentServiceDefinition:
      $ref: "./resources/payment_service_definition.yaml"
    PaymentServiceDefinitions:
      $ref: "./resources/payment_service_definitions.yaml"
    PaymentOption:
      $ref: "./resources/payment_option.yaml"
    PaymentOptions:
      $ref: "./resources/payment_options.yaml"
    PayPal:
      $ref: "./resources/paypal.yaml"
    # PayPal--Tokenized:
    #   $ref: "./resources/paypal--tokenized.yaml"
    PayPalDetails:
      $ref: "./resources/paypal_details.yaml"
    PayPalRequest:
      $ref: "./request-bodies/paypal_request.yaml"
    Session:
      $ref: "./resources/session.yaml"
    SessionRequest:
      $ref: "./request-bodies/session_create_request.yaml"
    Status:
      $ref: "./resources/status.yaml"
    Statuses:
      $ref: "./resources/statuses.yaml"
    TokenizedRequest:
      $ref: "./request-bodies/tokenized_request.yaml"
    Transaction:
      $ref: "./resources/transaction.yaml"
    Transactions:
      $ref: "./resources/transactions.yaml"
    TransactionsBatchCaptureRequest:
      $ref: "./request-bodies/transactions_batch_capture_request.yaml"
    TransactionRequest:
      $ref: "./request-bodies/transaction_create_request.yaml"
    TransactionCaptureRequest:
      $ref: "./request-bodies/transaction_capture_request.yaml"
    TransactionPaymentMethodRequest:
      $ref: "./request-bodies/transaction_payment_method_request.yaml"
    # TransactionEvent:
    #   $ref: "./resources/transaction_event.yaml"
    # TransactionEvents:
    #   $ref: "./resources/transaction_events.yaml"
    User:
      $ref: "./resources/user.yaml"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
